# Generated by Django 4.2.2 on 2023-06-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_chat', models.CharField(max_length=3000)),
                ('bot', models.CharField(default=None, max_length=3000)),
            ],
        ),
    ]
